---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 192.168.1.25
      ansible_user: aleks
      ansible_password: 1111
vector:
  hosts:
    vector-01:
      ansible_connection: 192.168.1.25
      ansible_user: aleks
      ansible_password: 1111
